/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_moemiku_xduilib_JNIBridgeForNativeActivity */

#ifndef _Included_com_moemiku_xduilib_JNIBridgeForNativeActivity
#define _Included_com_moemiku_xduilib_JNIBridgeForNativeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_moemiku_xduilib_JNIBridgeForNativeActivity
 * Method:    onIMEInputStr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_moemiku_xduilib_JNIBridgeForNativeActivity_onIMEInputStr
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif

void keepJNIBridgeSampleInApk();

#endif
